ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.vadla.online
CATALOGUE_HOST: catalogue-dev.vadla.online
REDIS_HOST: redis-dev.vadla.online
USER_HOST: user-dev.vadla.online
CART_HOST: cart-dev.vadla.online
MYSQL_HOST: mysql-dev.vadla.online
SHIPPING_HOST: shipping-dev.vadla.online
RABBITMQ_HOST: rabbitmq-dev.vadla.online
PAYMENT_HOST: payment-dev.vadla.online